version: "3.9"

services:

  kafka:
    image: bitnami/kafka:latest
    restart: unless-stopped
    ports: ["9092:9092"]
    env_file:
      - app-template.env

  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z-cpuv1
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # web-консоль
    env_file:
      - app-template.env

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports: ["5432:5432"]
    env_file:
      - app-template.env

  redis:
    image: redis:8.2-m01-alpine
    container_name: redis
    restart: unless-stopped
    ports: ["6379:6379"]
    env_file:
      - app-template.env

#  mongo: в этом сервисе не используется
#    image: mongo:7
#    restart: unless-stopped
#    ports: ["27017:27017"]
#    env_file:
#      - app-template.env
